from Xlib.keysymdef import miscellany, latin1

# class containing all the keysyms
class Keys:
    # reference link for keysym
    # https://www.oreilly.com/library/view/xlib-reference-manual/9780937175262/16_appendix-h.html
    def __init__(self):
        self.Backspace = miscellany.XK_BackSpace
        self.Tab = miscellany.XK_Tab
        self.Linefeed = miscellany.XK_Linefeed
        self.Clear = miscellany.XK_Clear
        self.Return = miscellany.XK_Return
        self.Pause = miscellany.XK_Pause
        self.Escape = miscellany.XK_Escape
        self.Delete = miscellany.XK_Delete
        self.Multi_key = miscellany.XK_Multi_key
        self.Kanji = miscellany.XK_Kanji
        self.Home = miscellany.XK_Home
        self.Left = miscellany.XK_Left
        self.Up = miscellany.XK_Up
        self.Right = miscellany.XK_Right
        self.Down = miscellany.XK_Down
        self.Prior = miscellany.XK_Prior
        self.Next = miscellany.XK_Next
        self.End = miscellany.XK_End
        self.Begin = miscellany.XK_Begin
        self.Select = miscellany.XK_Select
        self.Print = miscellany.XK_Print
        self.Execute = miscellany.XK_Execute
        self.Insert = miscellany.XK_Insert
        self.Undo = miscellany.XK_Undo
        self.Redo = miscellany.XK_Redo
        self.Menu = miscellany.XK_Menu
        self.Find = miscellany.XK_Find
        self.Cancel = miscellany.XK_Cancel
        self.Help = miscellany.XK_Help
        self.Break = miscellany.XK_Break
        self.Mode_switch = miscellany.XK_Mode_switch
        self.script_switch = miscellany.XK_script_switch
        self.Num_Lock = miscellany.XK_Num_Lock
        self.KP_Space = miscellany.XK_KP_Space
        self.KP_Tab = miscellany.XK_KP_Tab
        self.KP_Enter = miscellany.XK_KP_Enter
        self.KP_F1 = miscellany.XK_KP_F1
        self.KP_F2 = miscellany.XK_KP_F2
        self.KP_F3 = miscellany.XK_KP_F3
        self.KP_F4 = miscellany.XK_KP_F4
        self.KP_Equal = miscellany.XK_KP_Equal
        self.KP_Multiply = miscellany.XK_KP_Multiply
        self.KP_Add = miscellany.XK_KP_Add
        self.KP_Separator = miscellany.XK_KP_Separator
        self.KP_Subtract = miscellany.XK_KP_Subtract
        self.KP_Decimal = miscellany.XK_KP_Decimal
        self.KP_Divide = miscellany.XK_KP_Divide
        self.KP_0 = miscellany.XK_KP_0
        self.KP_1 = miscellany.XK_KP_1
        self.KP_2 = miscellany.XK_KP_2
        self.KP_3 = miscellany.XK_KP_3
        self.KP_4 = miscellany.XK_KP_4
        self.KP_5 = miscellany.XK_KP_5
        self.KP_6 = miscellany.XK_KP_6
        self.KP_7 = miscellany.XK_KP_7
        self.KP_8 = miscellany.XK_KP_8
        self.KP_9 = miscellany.XK_KP_9
        self.F1 = miscellany.XK_F1
        self.F2 = miscellany.XK_F2
        self.F3 = miscellany.XK_F3
        self.F4 = miscellany.XK_F4
        self.F5 = miscellany.XK_F5
        self.F6 = miscellany.XK_F6
        self.F7 = miscellany.XK_F7
        self.F8 = miscellany.XK_F8
        self.F9 = miscellany.XK_F9
        self.F10 = miscellany.XK_F10
        self.F11 = miscellany.XK_F11
        self.L1 = miscellany.XK_L1
        self.F12 = miscellany.XK_F12
        self.L2 = miscellany.XK_L2
        self.F13 = miscellany.XK_F13
        self.L3 = miscellany.XK_L3
        self.F14 = miscellany.XK_F14
        self.L4 = miscellany.XK_L4
        self.F15 = miscellany.XK_F15
        self.L5 = miscellany.XK_L5
        self.F16 = miscellany.XK_F16
        self.L6 = miscellany.XK_L6
        self.F17 = miscellany.XK_F17
        self.L7 = miscellany.XK_L7
        self.F18 = miscellany.XK_F18
        self.L8 = miscellany.XK_L8
        self.F19 = miscellany.XK_F19
        self.L9 = miscellany.XK_L9
        self.F20 = miscellany.XK_F20
        self.L10 = miscellany.XK_L10
        self.F21 = miscellany.XK_F21
        self.R1 = miscellany.XK_R1
        self.F22 = miscellany.XK_F22
        self.R2 = miscellany.XK_R2
        self.F23 = miscellany.XK_F23
        self.R3 = miscellany.XK_R3
        self.F24 = miscellany.XK_F24
        self.R4 = miscellany.XK_R4
        self.F25 = miscellany.XK_F25
        self.R5 = miscellany.XK_R5
        self.F26 = miscellany.XK_F26
        self.R6 = miscellany.XK_R6
        self.F27 = miscellany.XK_F27
        self.R7 = miscellany.XK_R7
        self.F28 = miscellany.XK_F28
        self.R8 = miscellany.XK_R8
        self.F29 = miscellany.XK_F29
        self.R9 = miscellany.XK_R9
        self.F30 = miscellany.XK_F30
        self.R10 = miscellany.XK_R10
        self.F31 = miscellany.XK_F31
        self.R11 = miscellany.XK_R11
        self.F32 = miscellany.XK_F32
        self.R12 = miscellany.XK_R12
        self.R13 = miscellany.XK_R13
        self.F33 = miscellany.XK_F33
        self.F34 = miscellany.XK_F34
        self.R14 = miscellany.XK_R14
        self.F35 = miscellany.XK_F35
        self.R15 = miscellany.XK_R15
        self.Shift_L = miscellany.XK_Shift_L
        self.Shift_R = miscellany.XK_Shift_R
        self.Control_L = miscellany.XK_Control_L
        self.Control_R = miscellany.XK_Control_R
        self.Caps_Lock = miscellany.XK_Caps_Lock
        self.Shift_Lock = miscellany.XK_Shift_Lock
        self.Meta_L = miscellany.XK_Meta_L
        self.Meta_R = miscellany.XK_Meta_R
        self.Alt_L = miscellany.XK_Alt_L
        self.Alt_R = miscellany.XK_Alt_R
        self.Super_L = miscellany.XK_Super_L
        self.Super_R = miscellany.XK_Super_R
        self.Hyper_L = miscellany.XK_Hyper_L
        self.Hyper_R = miscellany.XK_Hyper_R
        self.a=latin1.XK_a
        self.A=latin1.XK_A
        self.b=latin1.XK_b
        self.B=latin1.XK_B
        self.c=latin1.XK_c
        self.C=latin1.XK_C
        self.d=latin1.XK_d
        self.D=latin1.XK_D
        self.e=latin1.XK_e
        self.E=latin1.XK_E
        self.f=latin1.XK_f
        self.F=latin1.XK_F
        self.g=latin1.XK_g
        self.G=latin1.XK_G
        self.h=latin1.XK_h
        self.H=latin1.XK_H
        self.i=latin1.XK_i
        self.I=latin1.XK_I
        self.j=latin1.XK_j
        self.J=latin1.XK_J
        self.k=latin1.XK_k
        self.K=latin1.XK_K
        self.l=latin1.XK_l
        self.L=latin1.XK_L
        self.m=latin1.XK_m
        self.M=latin1.XK_M
        self.n=latin1.XK_n
        self.N=latin1.XK_N
        self.o=latin1.XK_o
        self.O=latin1.XK_O
        self.p=latin1.XK_p
        self.P=latin1.XK_P
        self.q=latin1.XK_q
        self.Q=latin1.XK_Q
        self.r=latin1.XK_r
        self.R=latin1.XK_R
        self.s=latin1.XK_s
        self.S=latin1.XK_S
        self.t=latin1.XK_t
        self.T=latin1.XK_T
        self.u=latin1.XK_u
        self.U=latin1.XK_U
        self.v=latin1.XK_v
        self.V=latin1.XK_V
        self.w=latin1.XK_w
        self.W=latin1.XK_W
        self.x=latin1.XK_x
        self.X=latin1.XK_X
        self.y=latin1.XK_y
        self.Y=latin1.XK_Y
        self.z=latin1.XK_z
        self.Z=latin1.XK_Z
        self.NUM_0=latin1.XK_0
        self.NUM_1=latin1.XK_1
        self.NUM_2=latin1.XK_2
        self.NUM_3=latin1.XK_3
        self.NUM_4=latin1.XK_4
        self.NUM_5=latin1.XK_5
        self.NUM_6=latin1.XK_6
        self.NUM_7=latin1.XK_7
        self.NUM_8=latin1.XK_8
        self.NUM_9=latin1.XK_9